docs_dir: ../docs
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
markdown_extensions:
- pymdownx.arithmatex:
    generic: true
nav:
- Home: index.md
- ğŸ“Statistics:
  - ğŸ“„ (1)Mean estimation and CLT: markdowns/(1)Mean estimation and CLT.md
  - ğŸ“„ (2)Prediction Interval and Confidence Interval: markdowns/(2)Prediction Interval
      and Confidence Interval.md
  - ğŸ“„ (3)Standard Error: markdowns/(3)Standard Error.md
  - ğŸ“„ (4)Linear Regression: markdowns/(4)Linear Regression.md
site_name: MSBA Knowledge Base
theme:
  name: material
