docs_dir: docs
extra_css:
- css/custom.css
- css/contributors.css
- css/admin.css
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://d3js.org/d3.v7.min.js
- js/api-config.js
- js/auth-utils.js
- js/admin-auth.js
- js/markdown-auth.js
- js/init-superuser.js
- js/auth.js
- js/graph.js
- js/contributors.js
- js/admin.js
- js/nav.js
markdown_extensions:
- pymdownx.arithmatex:
    generic: true
nav:
- ğŸ  Home: index.md
- ğŸ‘¤ Account:
    ğŸ‘‹ Profile: auth/profile.html
    ğŸ” Login: auth/login.html
- ğŸ–ï¸ Contributors: contributors.md
- âš™ï¸ Admin:
    ğŸ  Overview: admin/index.md
    ğŸ‘¥ User Management: admin/users.md
    ğŸ“„ Document Management: admin/documents.md
    ğŸ¥‡ Contributor Management: admin/contributors.md
- ğŸ“ Causal Inference:
  - ğŸ“„ AB Testing Framework With Regression: markdowns/AB Testing Framework With Regression.md
  - ğŸ“„ Difference in Difference: markdowns/Difference in Difference.md
  - ğŸ“„ Endogeneity and Exogeneity: markdowns/Endogeneity and Exogeneity.md
  - ğŸ“„ Fixed Effect: markdowns/Fixed Effect.md
  - ğŸ“„ Frisch Waugh Theorem: markdowns/Frisch Waugh Theorem.md
  - ğŸ“„ Instrument Variable: markdowns/Instrument Variable.md
  - ğŸ“„ Omitted Variable Bias: markdowns/Omitted Variable Bias.md
  - ğŸ“„ Using Control Variables: markdowns/Using Control Variables.md
- ğŸ“ Marketing Analytics:
  - ğŸ“„ Bass Model for Demand Prediction: markdowns/Bass Model for Demand Prediction.md
- ğŸ“ Statistics:
  - ğŸ“„ Hypothesis testing: markdowns/Hypothesis testing.md
  - ğŸ“„ Linear Regression and Coefficient: markdowns/Linear Regression and Coefficient.md
  - ğŸ“„ Standard Error: markdowns/Standard Error.md
  - ğŸ“„ Statistical Bias: markdowns/Statistical Bias.md
site_name: Zelkova
theme:
  favicon: assets/images/favicon.png
  features:
  - navigation.instant
  icon:
    logo: material/book
  logo: assets/images/logo.png
  name: material
