docs_dir: docs
extra_css:
- css/custom.css
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://d3js.org/d3.v7.min.js
- js/graph.js
markdown_extensions:
- pymdownx.arithmatex:
    generic: true
nav:
- Home: index.md
- Knowledge Graph: graph.html
- ğŸ“Prescriptive Modeling and Experiment:
  - ğŸ“„ A:B Testsing: markdowns/A:B Testsing.md
  - ğŸ“„ Causal Relationship: markdowns/Causal Relationship.md
  - ğŸ“„ Omitted Variable Bias: markdowns/Omitted Variable Bias.md
- ğŸ“Statistics:
  - ğŸ“„ Evaluation of Linear Regression: markdowns/Evaluation of Linear Regression.md
  - ğŸ“„ Hypothesis testing: markdowns/Hypothesis testing.md
  - ğŸ“„ Linear Regression: markdowns/Linear Regression.md
  - ğŸ“„ Mean estimation and CLT: markdowns/Mean estimation and CLT.md
  - ğŸ“„ Multiple Linear Regression: markdowns/Multiple Linear Regression.md
  - ğŸ“„ Prediction Interval and Confidence Interval: markdowns/Prediction Interval and
      Confidence Interval.md
  - ğŸ“„ Standard Error: markdowns/Standard Error.md
site_name: MSBA Knowledge Base
theme:
  name: material
