docs_dir: docs
extra_css:
- css/custom.css
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://d3js.org/d3.v7.min.js
- js/graph.js
markdown_extensions:
- pymdownx.arithmatex:
    generic: true
nav:
- Home: index.md
- ğŸ“Causal Inference:
  - ğŸ“„ AB Testing Framework With Regression: markdowns/AB Testing Framework With Regression.md
  - ğŸ“„ Difference in Difference: markdowns/Difference in Difference.md
  - ğŸ“„ Endogeneity and Exogeneity: markdowns/Endogeneity and Exogeneity.md
  - ğŸ“„ Fixed Effect: markdowns/Fixed Effect.md
  - ğŸ“„ Frisch Waugh Theorem: markdowns/Frisch Waugh Theorem.md
  - ğŸ“„ Instrument Variable: markdowns/Instrument Variable.md
  - ğŸ“„ Omitted Variable Bias: markdowns/Omitted Variable Bias.md
  - ğŸ“„ Using Control Variables: markdowns/Using Control Variables.md
- ğŸ“Marketing Analytics:
  - ğŸ“„ Bass Model: markdowns/Bass Model.md
- ğŸ“Statistics:
  - ğŸ“„ Hypothesis Testing: markdowns/Hypothesis Testing.md
  - ğŸ“„ Linear Regression and Coefficient: markdowns/Linear Regression and Coefficient.md
  - ğŸ“„ Standard Error: markdowns/Standard Error.md
  - ğŸ“„ Statistical Bias: markdowns/Statistical Bias.md
site_name: MSBA Knowledge Base
theme:
  name: material
